const SET_ROUTE_NAME = 'SET_ROUTE_NAME';
const SELECT_LANGUAGE = "SELECT_LANGUAGE";
const SET_HOME= 'SET_HOME';
const ADD_NOTE = 'ADD_NOTE';
const DELETE_NOTE = 'DELETE_NOTE';
const LOAD_NOTES= 'LOAD_NOTES'
export {
    SET_ROUTE_NAME,
    SELECT_LANGUAGE,
    SET_HOME,
    ADD_NOTE,
    DELETE_NOTE,
    LOAD_NOTES
}